## Sklearn 中的 Scaler 类

In [57]:
import numpy as np
from sklearn import datasets

In [58]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

导入 Scaler 类

In [60]:
from sklearn.preprocessing import StandardScaler

In [61]:
scaler = StandardScaler()
scaler.fit(X_train) # 把 X_train 丢进去进行归一化

StandardScaler()

In [62]:
scaler.mean_ # 表示数据中值

array([5.87232143, 3.04285714, 3.83303571, 1.2125    ])

In [63]:
scaler.scale_ # 表示数据分布范围

array([0.80125012, 0.44314507, 1.7379888 , 0.7473913 ])

In [64]:
X_std_train = scaler.transform(X_train)
X_std_test = scaler.transform(X_test)
# 必须经过赋值才可进行归一化

In [65]:
X_std_train[:10] 

array([[-0.58948063, -0.09671132,  0.38375638,  0.38467132],
       [ 1.65700889, -0.09671132,  1.13174739,  0.51847005],
       [-0.46467566,  1.03158738, -1.45745227, -1.35471206],
       [ 0.28415418, -0.99935027,  1.01667185,  0.2508726 ],
       [ 1.157789  ,  0.35460816,  1.18928516,  1.4550611 ],
       [-0.21506571, -0.09671132,  0.21114307, -0.01672484],
       [-1.08870053, -1.67632948, -0.30669686, -0.28432228],
       [-0.09026074, -0.77369053,  0.728983  ,  0.91986621],
       [ 1.65700889,  0.35460816,  1.24682293,  0.78606749],
       [-0.21506571, -1.22501001,  0.67144523,  1.05366493]])

In [66]:
from sklearn.neighbors import KNeighborsClassifier

In [70]:
knn_clf = KNeighborsClassifier(3, weights='distance')
knn_clf.fit(X_std_train, y_train) # 用归一化之后的数据集训练

KNeighborsClassifier(n_neighbors=3, weights='distance')

In [72]:
knn_clf.score(X_std_test, y_test)

0.9736842105263158